include theos/makefiles/common.mk

TOOL_NAME = getappdir
getappdir_FILES = /mnt/d/codes/cmdsapp/getappdir/main.mm
getappdir_FRAMEWORKS = UIKit Foundation MobileCoreServices
getappdir_PRIVATE_FRAMEWORKS = 
getappdir_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/tool.mk
