include theos/makefiles/common.mk

TOOL_NAME = getapplist
getapplist_FILES = /mnt/d/codes/cmdsapp/getapplist/main.mm
getapplist_FRAMEWORKS = UIKit Foundation MobileCoreServices
getapplist_PRIVATE_FRAMEWORKS = 
getapplist_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/tool.mk
